name: streamlit-docker-build

env:
  SERVICE_NAME: mikegpt
  DOCKER_IMAGE: mdh266/mikegpt

on:
  push:
    branches:
      - "main"
    paths:
    - Dockerfile
    - src/main.py
    - src/utils.py
    - .github/workflows/docker-build.yaml

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker
        run: | 
          docker build -t ${{ env.DOCKER_IMAGE }}:cloudrun .
          docker push ${{ env.DOCKER_IMAGE }}:cloudrun 

          - name: Google Cloud Auth
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
  
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $SERVICE_NAME \
            --image=${{ env.DOCKER_IMAGE }}:cloudrun \
            --set-env-vars=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
            --region=us-central1 \
            --project=${{ secrets.GOOGLE_PROJECT_ID }} 
